#!/usr/bin/env python3
"""Regenerate every static book figure into publication/figures/.

Each ``tools/figures/<widget>.py`` (all files except ``_style.py`` and this
runner) reproduces one interactive web widget's default-state mathematics in
JAX and writes ``publication/figures/<widget>.pdf``. The PDF build
(``tools/build-publication.mjs``) embeds those plates in place of the widgets.

Usage:
    python3 tools/figures/build_figures.py            # all figures
    python3 tools/figures/build_figures.py sig_draw   # one, by module name
"""
from __future__ import annotations

import os
import sys
import hashlib
import json
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKIP = {"_style.py", "_tikz.py", Path(__file__).name}
ROOT = HERE.parents[1]
MANIFEST = ROOT / "publication" / "figures" / "artifacts.json"
# Some figure modules import pyplot before _style. Establish the writable,
# project-local cache before running any module so font discovery happens once.
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".context" / "matplotlib"))


def scripts(selection: list[str]) -> list[Path]:
    files = sorted(p for p in HERE.glob("*.py") if p.name not in SKIP)
    if selection:
        wanted = {s.removesuffix(".py") for s in selection}
        files = [p for p in files if p.stem in wanted]
    return files


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def source_sha256(path: Path) -> str:
    """Hash a wrapper together with its optional authored TikZ source."""
    digest = hashlib.sha256(path.read_bytes())
    tikz = path.with_suffix(".tex")
    if tikz.exists():
        digest.update(tikz.read_bytes())
    return digest.hexdigest()


def style_sha256(source: Path) -> str:
    """Hash only the rendering engine used by this source."""
    if source.with_suffix(".tex").exists():
        digest = hashlib.sha256((HERE / "_tikz.py").read_bytes())
        digest.update((HERE / "tikz-style.tex").read_bytes())
    else:
        digest = hashlib.sha256((HERE / "_style.py").read_bytes())
    return digest.hexdigest()


def write_manifest(built: list[Path], *, full_build: bool) -> None:
    """Record hashes only for artifacts regenerated by this invocation.

    Preserving old records during a partial build is intentional: if the
    shared engine changed, untouched plates retain the old style hash and the
    integrity check correctly demands a full regeneration.
    """
    if full_build or not MANIFEST.exists():
        records = {}
    else:
        records = json.loads(MANIFEST.read_text()).get("figures", {})
    live_ids = {source.stem.replace("_", "-") for source in scripts([])}
    records = {figure_id: record for figure_id, record in records.items()
               if figure_id in live_ids}
    for source in built:
        figure_id = source.stem.replace("_", "-")
        svg = ROOT / "public" / "figures" / f"{figure_id}.svg"
        pdf = ROOT / "publication" / "figures" / f"{figure_id}.pdf"
        if svg.exists() and pdf.exists():
            records[figure_id] = {
                "source": str(source.relative_to(ROOT)),
                "source_sha256": source_sha256(source),
                "style_sha256": style_sha256(source),
                "svg_sha256": sha256(svg),
                "pdf_sha256": sha256(pdf),
            }
    MANIFEST.write_text(json.dumps({"version": 1, "figures": records}, indent=2) + "\n")


def main() -> int:
    files = scripts(sys.argv[1:])
    if not files:
        print("no matching figure scripts", file=sys.stderr)
        return 1
    failed = []
    for path in files:
        env = {
            **os.environ,
            "PYTHONHASHSEED": "0",
            "JAX_ENABLE_X64": "true",
            "JAX_PLATFORM_NAME": os.environ.get("JAX_PLATFORM_NAME", "cpu"),
        }
        try:
            subprocess.run([sys.executable, str(path)], cwd=ROOT, env=env, check=True)
            print(f"  ok   {path.stem}")
        except subprocess.CalledProcessError as exc:  # keep going; report at the end
            failed.append((path.stem, exc.returncode))
            print(f"  FAIL {path.stem}: exit {exc.returncode}", file=sys.stderr)
    if not failed:
        write_manifest(files, full_build=not sys.argv[1:])
    print(f"\n{len(files) - len(failed)}/{len(files)} figures built.")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
