"""cme-explore: the empirical conditional mean embedding at a fixed x*.

Reproduces ``public/assets/viz-cme-explore.js`` at its default state. Sixty
fixed samples (x_i, y_i) are generated by the widget's seeded LCG. With RBF
kernels k on X (bandwidth 0.5) and l on Y (bandwidth 0.4), the embedded
conditional at the default conditioning point x* = 0.5 is

    mu_{Y|x*} = sum_i beta_i(x*) l(., y_i),
    beta(x*)  = (K_X + n lambda I)^{-1} k_X(x*),   lambda = 10^{-2}.

This is the exact regularized solve the widget runs (its one-time Cholesky
factor of K_X + n lambda I is just an efficient way to apply that inverse).
The main panel shows the samples, the conditional-mean curve x -> E[Y|X=x],
the vertical line at x*, and the dot marking E[Y|X=x*]. The side panel is the
embedded conditional density profile sum_i beta_i l(., y_i) over y.
"""
from __future__ import annotations

import jax
import jax.numpy as jnp
import numpy as np
from matplotlib.gridspec import GridSpec
import matplotlib.pyplot as plt

import _style as S

jax.config.update("jax_enable_x64", True)
S.apply_style()

# --- widget constants --------------------------------------------------------
N = 60           # number of fixed samples
LY = 0.4         # RBF bandwidth on Y (fixed in the JS)
BW = 0.5         # default X bandwidth slider value
LAM = 1e-2       # default ridge: 10^(log10 lambda = -2)
XSTAR = 0.5      # default conditioning point x*


def make_samples():
    """Exact seeded LCG + Box-Muller from the JS, giving the same 60 samples."""
    seed = 0x9D2C5680

    def rnd():
        nonlocal seed
        seed = (seed * 1664525 + 1013904223) & 0xFFFFFFFF
        return seed / 4294967296.0

    def gauss():
        u = max(rnd(), 1e-9)
        v = rnd()
        return np.sqrt(-2.0 * np.log(u)) * np.cos(2.0 * np.pi * v)

    xs = np.empty(N)
    ys = np.empty(N)
    for i in range(N):
        x = -3.0 + 6.0 * (i + 0.5) / N + 0.05 * gauss()
        xs[i] = x
        ys[i] = np.sin(1.2 * x) + 0.3 * x + 0.15 * (1.0 + abs(x) / 3.0) * gauss()
    return xs, ys


def kX(a, b, bw):
    """RBF kernel on X."""
    d = a[:, None] - b[None, :]
    return jnp.exp(-(d ** 2) / (2.0 * bw * bw))


def beta_at(xs, xstar, bw, lam):
    """Exact CME weights beta(x*) = (K_X + n lambda I)^{-1} k_X(x*)."""
    n = xs.shape[0]
    KX = kX(xs, xs, bw)
    kx = kX(jnp.array([xstar]), xs, bw)[0]              # k_X(x*)
    return jnp.linalg.solve(KX + n * lam * jnp.eye(n), kx)


def mean_curve(xs, ys, grid, bw, lam):
    """Conditional-mean curve x -> sum_i beta_i(x) y_i over a grid of x."""
    n = xs.shape[0]
    KX = kX(xs, xs, bw)
    A = KX + n * lam * jnp.eye(n)
    kg = kX(grid, xs, bw)                                # (G, n) test vectors
    B = jnp.linalg.solve(A, kg.T)                        # columns beta(x_g)
    return B.T @ ys


def main() -> str:
    xs_np, ys_np = make_samples()
    xs = jnp.asarray(xs_np)
    ys = jnp.asarray(ys_np)

    # conditional-mean regression curve over x in [-3, 3]
    gridx = jnp.linspace(-3.0, 3.0, 150)
    mcurve = np.asarray(mean_curve(xs, ys, gridx, BW, LAM))

    # CME weights at the default conditioning point, and its conditional mean
    beta = beta_at(xs, XSTAR, BW, LAM)
    mstar = float(beta @ ys)

    # embedded conditional profile sum_i beta_i l(., y_i) over the y grid
    ygrid = jnp.linspace(-2.6, 2.6, 120)
    dl = ygrid[:, None] - ys[None, :]
    lY = jnp.exp(-(dl ** 2) / (2.0 * LY * LY))
    prof = np.asarray(lY @ beta)
    ygrid_np = np.asarray(ygrid)

    fig = plt.figure(figsize=(5.6, 3.2))
    gs = GridSpec(1, 2, width_ratios=[4.2, 1.0], wspace=0.06, figure=fig)

    # --- main panel: samples, conditional-mean curve, x*, and its mean --------
    ax = fig.add_subplot(gs[0])
    ax.scatter(xs_np, ys_np, s=14, color=S.MUTED, alpha=0.55,
               edgecolor="none", zorder=2)
    ax.plot(np.asarray(gridx), mcurve, color=S.POS, lw=1.8, zorder=3,
            label=r"$x\mapsto\widehat{\mathbb{E}}[Y\mid X=x]$")
    ax.axvline(XSTAR, color=S.ACCENT, lw=1.3, zorder=3)
    ax.scatter([XSTAR], [mstar], s=40, color=S.ACCENT,
               edgecolor=S.PAPER, linewidth=1.0, zorder=5,
               label=r"$\widehat{\mathbb{E}}[Y\mid X=x^*]$")
    ax.set_xlim(-3, 3)
    ax.set_ylim(-2.6, 2.6)
    ax.set_xlabel("$x$")
    ax.set_ylabel("$y$")
    ax.legend(loc="upper left", frameon=False, fontsize=7.5)
    S.finish(ax)

    # --- side panel: embedded conditional profile at x* ----------------------
    axp = fig.add_subplot(gs[1], sharey=ax)
    pmax = max(float(np.max(np.abs(prof))), 1e-9)
    axp.fill_betweenx(ygrid_np, 0.0, np.maximum(prof, 0.0) / pmax,
                      color=S.ACCENT, alpha=0.15, zorder=1)
    axp.plot(np.maximum(prof, 0.0) / pmax, ygrid_np,
             color=S.ACCENT, lw=1.6, zorder=2)
    axp.axhline(mstar, color=S.ACCENT, lw=0.9, ls=(0, (3, 3)), zorder=3)
    axp.set_xlim(0, 1.05)
    axp.set_xticks([])
    axp.tick_params(labelleft=False)
    axp.set_title(r"$\sum_i\beta_i\,l(\cdot,y_i)$", fontsize=8, pad=4,
                  color=S.INK)
    for side in ("top", "right", "bottom"):
        axp.spines[side].set_visible(False)
    axp.spines["left"].set_color(S.RULE)

    fig.suptitle(
        r"Conditional mean embedding at $x^*=0.5$, "
        r"$\beta=(K_X+n\lambda I)^{-1}k_X(x^*)$",
        color=S.INK, fontsize=9.5, y=1.02)

    return S.save(fig, "cme-explore")


if __name__ == "__main__":
    print(main())
