"""influence-glow: exact per-point influence on a kernel-ridge prediction.

Reproduces ``public/assets/viz-influence-glow.js`` at its default state. Fifteen
points x_i = -3 + 6(i+1/2)/15 + jitter carry noisy labels y_i = sin(1.2 x_i)+eps,
generated by the widget's own linear-congruential stream (seed 0x1ce) so the data
matches the browser exactly. A Gaussian kernel (bandwidth ELL=0.5) is fit by
kernel ridge with ridge RIDGE=0.08: G = (K + lambda I)^{-1}, alpha = G y, hat
matrix H = K G.

At the default query x* = 0.7 each training point "glows" by its exact influence
-- the closed-form change in f(x*) if that point were deleted,

    delta_i(x*) = (G k*)_i * (y_i - yhat_i) / (1 - H_ii),

the same rank-one identity the widget draws (glow[i] = (G k*)_i * loo[i]). This
equals a brute-force leave-one-out refit to machine precision; the right panel
plots the closed-form deletion effect against an explicit refit for every point.

Math in JAX (float64); brute-force refits reuse the same JAX solver.
"""
from __future__ import annotations

import jax
import jax.numpy as jnp
import numpy as np
from matplotlib.gridspec import GridSpec
import matplotlib.pyplot as plt

import _style as S

jax.config.update("jax_enable_x64", True)
S.apply_style()

# widget constants (viz-influence-glow.js)
N, ELL, RIDGE = 15, 0.5, 0.08
XSTAR = 0.7                       # default query position


def widget_data() -> tuple[np.ndarray, np.ndarray]:
    """Regenerate the widget's data with its exact LCG stream (seed 0x1ce)."""
    seed = 0x1ce

    def rnd() -> float:
        nonlocal seed
        seed = (seed * 1103515245 + 12345) & 0x7fffffff
        return seed / 0x7fffffff

    xs = np.empty(N); ys = np.empty(N)
    for i in range(N):                              # x then y drawn per point
        x = -3.0 + 6.0 * (i + 0.5) / N + 0.25 * (rnd() - 0.5)
        xs[i] = x
        ys[i] = np.sin(1.2 * x) + 0.15 * (rnd() - 0.5)
    return xs, ys


def gaussian(a: jnp.ndarray, b: jnp.ndarray, ell: float) -> jnp.ndarray:
    d = a[:, None] - b[None, :]
    return jnp.exp(-(d ** 2) / (2.0 * ell * ell))


def fit(xs, ys):
    """Kernel ridge solve exactly as the widget forms it (G = (K+lambda I)^-1)."""
    K = gaussian(xs, xs, ELL)
    # Solve against the identity because the full inverse action is required by
    # the exact leave-one-out diagonal; never form it through ``inv``.
    G = jnp.linalg.solve(K + RIDGE * jnp.eye(N), jnp.eye(N))
    alpha = G @ ys                                  # representer weights
    yhat = K @ alpha                                # smoothed fit  = H y
    H = K @ G                                        # hat matrix
    hdiag = jnp.diag(H)                             # leverages H_ii
    loo = (ys - yhat) / (1.0 - hdiag)              # closed-form LOO residuals
    return K, G, alpha, yhat, hdiag, loo


def influence(G, loo, xs, ys, alpha, xstar):
    """glow_i = (G k*)_i * loo_i  -- exact deletion effect on f(x*)."""
    kstar = gaussian(jnp.array([xstar]), xs, ELL)[0]
    fstar = jnp.dot(alpha, kstar)
    Gk = G @ kstar
    glow = Gk * loo
    return kstar, fstar, glow


def brute_force_deletion(xs, ys, alpha, xstar, fstar):
    """f(x*) - f^{-i}(x*) by an explicit refit dropping each point in turn."""
    delta = np.empty(N)
    for i in range(N):
        keep = np.array([j for j in range(N) if j != i])
        xk = jnp.asarray(xs[keep]); yk = jnp.asarray(ys[keep])
        Kk = gaussian(xk, xk, ELL)
        ak = jnp.linalg.solve(Kk + RIDGE * jnp.eye(N - 1), yk)
        kk = gaussian(jnp.array([xstar]), xk, ELL)[0]
        fi = float(jnp.dot(ak, kk))
        delta[i] = float(fstar) - fi
    return delta


def main() -> str:
    xs_np, ys_np = widget_data()
    xs = jnp.asarray(xs_np); ys = jnp.asarray(ys_np)

    K, G, alpha, yhat, hdiag, loo = fit(xs, ys)
    kstar, fstar, glow = influence(G, loo, xs, ys, alpha, XSTAR)
    glow = np.asarray(glow); fstar = float(fstar)

    # closed-form deletion effect (= glow) vs brute-force refit, to machine eps
    delta_bf = brute_force_deletion(xs_np, ys_np, alpha, XSTAR, fstar)
    max_disc = float(np.max(np.abs(delta_bf - glow)))
    print(f"max |brute-force refit - closed-form influence| = {max_disc:.2e}")

    # fitted curve on a dense grid
    grid = jnp.linspace(-3.4, 3.4, 400)
    fgrid = np.asarray(gaussian(grid, xs, ELL) @ alpha)
    grid = np.asarray(grid)

    order = np.argsort(-np.abs(glow))               # ranking by |influence|
    gmax = max(np.max(np.abs(glow)), 1e-9)

    fig = plt.figure(figsize=(7.2, 3.2))
    gs = GridSpec(1, 2, width_ratios=[3.1, 2.0], wspace=0.32, figure=fig)

    # -- panel A: the glow plate ------------------------------------------
    ax = fig.add_subplot(gs[0])
    ax.axhline(0.0, color=S.RULE, lw=0.8, ls=(0, (3, 3)))
    ax.plot(grid, fgrid, color=S.ACCENT, lw=1.8, zorder=2)
    # dashed query line + prediction dot
    ax.axvline(XSTAR, color=S.MUTED, lw=1.1, ls=(0, (3, 3)), zorder=1)
    ax.scatter([XSTAR], [fstar], s=48, color=S.ACCENT,
               edgecolor=S.PAPER, linewidth=1.0, zorder=6)
    # training points: translucent halo sized by |influence|, blue +/red -
    for i in range(N):
        t = abs(glow[i]) / gmax
        c = S.POS if glow[i] >= 0 else S.NEG
        if t > 0.04:
            ax.scatter([xs_np[i]], [ys_np[i]], s=(6 + 60 * t) ** 2 / 6,
                       color=c, alpha=0.28 * t, linewidth=0, zorder=3)
        ax.scatter([xs_np[i]], [ys_np[i]], s=26, color=c,
                   edgecolor=S.PAPER, linewidth=0.8, zorder=5)
    # rank the top-3 most influential points
    for r in range(3):
        i = order[r]
        ax.annotate(f"#{r + 1}", (xs_np[i], ys_np[i]),
                    xytext=(0, 9 + 14 * (abs(glow[i]) / gmax)),
                    textcoords="offset points", ha="center",
                    fontsize=7.5, color=S.MUTED, zorder=7)
    ax.set_xlim(-3.4, 3.4); ax.set_ylim(-1.6, 1.6)
    ax.set_xlabel("$x$"); ax.set_ylabel("$f(x)$")
    ax.set_title(r"Influence on $f(x_\star)$, $x_\star=0.7$", color=S.INK)
    S.finish(ax)

    # -- panel B: closed form matches brute-force refit -------------------
    axb = fig.add_subplot(gs[1])
    lim = float(np.max(np.abs(delta_bf))) * 1.15
    axb.plot([-lim, lim], [-lim, lim], color=S.RULE, lw=0.9, zorder=1)
    axb.scatter(glow, delta_bf, s=22, color=S.POS,
                edgecolor=S.PAPER, linewidth=0.6, zorder=3)
    axb.set_xlim(-lim, lim); axb.set_ylim(-lim, lim)
    axb.set_aspect("equal")
    axb.set_xlabel(r"closed-form $\delta_i(x_\star)$")
    axb.set_ylabel(r"brute-force refit")
    axb.set_title("LOO deletion effect", color=S.INK)
    mant, exp = f"{max_disc:.0e}".split("e")
    axb.text(0.0, -lim * 0.82,
             rf"max discrepancy $\approx {mant}\times10^{{{int(exp)}}}$",
             ha="center", va="center", fontsize=7.5, color=S.MUTED)
    S.finish(axb)

    return S.save(fig, "influence-glow")


if __name__ == "__main__":
    print(main())
