import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const copy = (source, target) => {
  const destination = path.join(root, target);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.copyFileSync(path.join(root, source), destination);
};

copy("node_modules/katex/dist/katex.min.css", "public/vendor/katex/katex.min.css");
copy("node_modules/katex/dist/katex.min.js", "public/vendor/katex/katex.min.js");
copy("node_modules/katex/dist/contrib/auto-render.min.js", "public/vendor/katex/auto-render.min.js");
fs.cpSync(path.join(root, "node_modules/katex/dist/fonts"), path.join(root, "public/vendor/katex/fonts"), { recursive: true });

const fontFiles = [
  "stix-two-text-latin-400-normal.woff2", "stix-two-text-latin-400-italic.woff2",
  "stix-two-text-latin-ext-400-normal.woff2",
  "stix-two-text-latin-600-normal.woff2", "stix-two-text-latin-600-italic.woff2",
  "stix-two-text-latin-700-normal.woff2", "stix-two-text-latin-700-italic.woff2",
];
for (const file of fontFiles) copy(`node_modules/@fontsource/stix-two-text/files/${file}`, `public/vendor/fonts/${file}`);
for (const file of [
  "ibm-plex-sans-latin-400-normal.woff2", "ibm-plex-sans-latin-400-italic.woff2",
  "ibm-plex-sans-latin-500-normal.woff2", "ibm-plex-sans-latin-600-normal.woff2",
]) copy(`node_modules/@fontsource/ibm-plex-sans/files/${file}`, `public/vendor/fonts/${file}`);
for (const file of [
  "source-serif-4-latin-400-normal.woff2", "source-serif-4-latin-400-italic.woff2",
  "source-serif-4-latin-ext-400-normal.woff2",
  "source-serif-4-latin-600-normal.woff2", "source-serif-4-latin-600-italic.woff2",
  "source-serif-4-latin-700-normal.woff2",
]) copy(`node_modules/@fontsource/source-serif-4/files/${file}`, `public/vendor/fonts/${file}`);
for (const file of [
  "ibm-plex-mono-latin-400-normal.woff2", "ibm-plex-mono-latin-500-normal.woff2",
  "ibm-plex-mono-latin-600-normal.woff2",
]) copy(`node_modules/@fontsource/ibm-plex-mono/files/${file}`, `public/vendor/fonts/${file}`);

const css = `/* Generated by tools/vendor-assets.mjs. */
@font-face{font-family:'STIX Two Text';font-style:normal;font-weight:400;src:url('../vendor/fonts/stix-two-text-latin-ext-400-normal.woff2') format('woff2');font-display:swap;unicode-range:U+0100-024F}
@font-face{font-family:'STIX Two Text';font-style:normal;font-weight:400;src:url('../vendor/fonts/stix-two-text-latin-400-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'STIX Two Text';font-style:italic;font-weight:400;src:url('../vendor/fonts/stix-two-text-latin-400-italic.woff2') format('woff2');font-display:swap}
@font-face{font-family:'STIX Two Text';font-style:normal;font-weight:600;src:url('../vendor/fonts/stix-two-text-latin-600-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'STIX Two Text';font-style:italic;font-weight:600;src:url('../vendor/fonts/stix-two-text-latin-600-italic.woff2') format('woff2');font-display:swap}
@font-face{font-family:'STIX Two Text';font-style:normal;font-weight:700;src:url('../vendor/fonts/stix-two-text-latin-700-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'STIX Two Text';font-style:italic;font-weight:700;src:url('../vendor/fonts/stix-two-text-latin-700-italic.woff2') format('woff2');font-display:swap}
@font-face{font-family:'IBM Plex Sans';font-style:normal;font-weight:400;src:url('../vendor/fonts/ibm-plex-sans-latin-400-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'IBM Plex Sans';font-style:italic;font-weight:400;src:url('../vendor/fonts/ibm-plex-sans-latin-400-italic.woff2') format('woff2');font-display:swap}
@font-face{font-family:'IBM Plex Sans';font-style:normal;font-weight:500;src:url('../vendor/fonts/ibm-plex-sans-latin-500-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'IBM Plex Sans';font-style:normal;font-weight:600;src:url('../vendor/fonts/ibm-plex-sans-latin-600-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'Source Serif 4';font-style:normal;font-weight:400;src:url('../vendor/fonts/source-serif-4-latin-400-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'Source Serif 4';font-style:normal;font-weight:400;src:url('../vendor/fonts/source-serif-4-latin-ext-400-normal.woff2') format('woff2');font-display:swap;unicode-range:U+0100-024F}
@font-face{font-family:'Source Serif 4';font-style:italic;font-weight:400;src:url('../vendor/fonts/source-serif-4-latin-400-italic.woff2') format('woff2');font-display:swap}
@font-face{font-family:'Source Serif 4';font-style:normal;font-weight:600;src:url('../vendor/fonts/source-serif-4-latin-600-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'Source Serif 4';font-style:italic;font-weight:600;src:url('../vendor/fonts/source-serif-4-latin-600-italic.woff2') format('woff2');font-display:swap}
@font-face{font-family:'Source Serif 4';font-style:normal;font-weight:700;src:url('../vendor/fonts/source-serif-4-latin-700-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'IBM Plex Mono';font-style:normal;font-weight:400;src:url('../vendor/fonts/ibm-plex-mono-latin-400-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'IBM Plex Mono';font-style:normal;font-weight:500;src:url('../vendor/fonts/ibm-plex-mono-latin-500-normal.woff2') format('woff2');font-display:swap}
@font-face{font-family:'IBM Plex Mono';font-style:normal;font-weight:600;src:url('../vendor/fonts/ibm-plex-mono-latin-600-normal.woff2') format('woff2');font-display:swap}
`;
fs.writeFileSync(path.join(root, "public/assets/vendor.css"), css);
console.log("Vendored KaTeX and book fonts.");
